### ISSUE TITLE
Latest FBGEMM doesn't build with latest PyTorch

### ISSUE THREAD

**Issue by ezyang** [pytorch/FBGEMM#2318] opened 2024-02-07 14:54 UTC
Failure:

```
FAILED: CMakeFiles/fbgemm_gpu_py.dir/src/sparse_ops/sparse_ops_cpu.cpp.o                                                           /usr/bin/c++ -DUSE_C10D_GLOO -DUSE_C10D_NCCL -DUSE_DISTRIBUTED -DUSE_RPC -DUSE_TENSORPIPE -Dfbgemm_gpu_py_EXPORTS -I/data/users/ezy
ang/b/FBGEMM/fbgemm_gpu -I/data/users/ezyang/b/FBGEMM/fbgemm_gpu/include -I/data/users/ezyang/b/FBGEMM/fbgemm_gpu/../include -I/dat
a/users/ezyang/b/FBGEMM/fbgemm_gpu/../third_party/asmjit/src -I/data/users/ezyang/b/FBGEMM/fbgemm_gpu/../third_party/cpuinfo/includ
e -isystem /data/users/ezyang/b/pytorch/torch/include -isystem /data/users/ezyang/b/pytorch/torch/include/torch/csrc/api/include -i
system /usr/local/cuda-12.0/include -D_GLIBCXX_USE_CXX11_ABI=1 -O3 -DNDEBUG -std=c++17 -fPIC -D_GLIBCXX_USE_CXX11_ABI=1 -mavx -mf16
c -mfma -mavx2 -fopenmp -MD -MT CMakeFiles/fbgemm_gpu_py.dir/src/sparse_ops/sparse_ops_cpu.cpp.o -MF CMakeFiles/fbgemm_gpu_py.dir/s
rc/sparse_ops/sparse_ops_cpu.cpp.o.d -o CMakeFiles/fbgemm_gpu_py.dir/src/sparse_ops/sparse_ops_cpu.cpp.o -c /data/users/ezyang/b/FB
GEMM/fbgemm_gpu/src/sparse_ops/sparse_ops_cpu.cpp                                                                                  
/data/users/ezyang/b/FBGEMM/fbgemm_gpu/src/sparse_ops/sparse_ops_cpu.cpp: In function ‘Tensor fbgemm_gpu::native_empty_like(const T
ensor&)’:                                                                                                                          
/data/users/ezyang/b/FBGEMM/fbgemm_gpu/src/sparse_ops/sparse_ops_cpu.cpp:131:7: error: ‘optTypeMetaToScalarType’ was not declared i
n this scope; did you mean ‘c10::optTypeMetaToScalarType’?                                                                         
  131 |       optTypeMetaToScalarType(self.options().dtype_opt()),                                        
      |       ^~~~~~~~~~~~~~~~~~~~~~~                                                                                              
      |       c10::optTypeMetaToScalarType 
```

**Comment by q10** [comment] 2024-02-07 19:45
This is similar to https://github.com/pytorch/pytorch/pull/115623, but the fbgemm appears to already have the fix: https://github.com/pytorch/FBGEMM/blob/17a06044d40c6ac7ec3be0c3f2adfda01e8bb9fd/fbgemm_gpu/src/sparse_ops/sparse_ops_cpu.cpp#L131

Are you using an older version of fbgemm_gpu?

**Comment by q10** [comment] 2024-06-11 04:34
Closing, as the issue appears to be resolved.  Please feel free to open a new ticket if the issue is observed again.

**Closed by q10** 2024-06-11 04:34 UTC
