### ISSUE TITLE
Installing from source gives me an OS: bgemm_gpu/fbgemm_gpu_py.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by YLGH** [pytorch/FBGEMM#1126] opened 2022-05-17 03:23 UTC
Hey folks,

I'm installing fbgemm_gpu from torchrec's third party directory

I've run python setup.py clean, as well as as the install command
python setup.py

However, during
import fbgemm_gpu

I see a

```
fbgemm_gpu/fbgemm_gpu_py.so: cannot open shared object file: No such file or directory
```

error

**Comment by geyyer** [comment] 2022-05-19 15:57
Hi @YLGH, thanks for reporting! Could you share exact steps so that we could reproduce the issue?

**Comment by MohammadMahdiJavanmard** [comment] 2022-06-10 18:13
@YLGH could you please share the installation instructions? After installing PyTorch, there are building/installation instructions that you should execute to generate this shared object file (fbgemm_gpu_py.so). I am afraid, you forgot to run those FBGEMM_GPU specific instructions. Also, could you please run "pip list" to ensure that fbgemm is installed (also if it is installed, in the installation directory, you should be able to find this file)?

**Comment by jianyuh** [comment] 2022-07-09 20:59
Closing since this issue isn't updated for a while.

**Closed by jianyuh** 2022-07-09 20:59 UTC
