### ISSUE TITLE
Undefined symbol _ZN6asmjit8_abi_1_910JitRuntimeD1Ev

### ISSUE THREAD

**Issue by ezyang** [pytorch/FBGEMM#1936] opened 2023-08-14 17:30 UTC
This happens when you don't init submodules. We should error if you haven't init'ed submodules instead.

**Comment by spcyppt** [comment] 2023-08-14 22:58
Thank you @ezyang. We will work on it.

**Comment by q10** [comment] 2023-12-14 00:07
It looks like this issue has been fixed, as we have been unable to reproduce the problem.  Closing this issue

**Closed by q10** 2023-12-14 00:07 UTC
